### ISSUE TITLE
Adopt formatOnSave changes

### ISSUE THREAD

**Issue by jrieken** [leftstick/vscode-esformatter#2]
Since version 1.6 VS Code has a format on save option. It works by calling the registered formatting provider for the language in question and most _importantly_ it happens _before_ the file is saved to disk, not causing additional fs writes and event cascades. 

Please adopt [this code](https://github.com/leftstick/vscode-esformatter/blob/master/client/actions.js#L30) code by either removing it and trusting the new `editor.formatOnSave`-setting or by using the new `onWillSaveTextDocument`-event. 

See https://code.visualstudio.com/updates#_format-on-save, https://github.com/Microsoft/vscode/issues/12449, and https://github.com/Microsoft/vscode/issues/239 for more details

**Comment by leftstick** [comment]
Thanks for notifying, updated with trusting `editor.formatOnSave` option
